/* generated by scripts/record-fixtures.mjs — do not edit */
import f0 from '../fixtures/collaborators/lumen/lumen.json' with { type: 'json' };
import f1 from '../fixtures/collaborators/signalxjs/pulse.json' with { type: 'json' };
import f2 from '../fixtures/issues/lumen/lumen.json' with { type: 'json' };
import f3 from '../fixtures/issues/signalxjs/pulse.json' with { type: 'json' };
import f4 from '../fixtures/labels/lumen/lumen.json' with { type: 'json' };
import f5 from '../fixtures/labels/signalxjs/pulse.json' with { type: 'json' };
import f6 from '../fixtures/milestones/lumen/lumen.json' with { type: 'json' };
import f7 from '../fixtures/milestones/signalxjs/pulse.json' with { type: 'json' };
import f8 from '../fixtures/owner-repos/signalxjs.json' with { type: 'json' };
import f9 from '../fixtures/repo/lumen/lumen.json' with { type: 'json' };
import f10 from '../fixtures/repo/signalxjs/core.json' with { type: 'json' };
import f11 from '../fixtures/repo/signalxjs/pulse.json' with { type: 'json' };
import f12 from '../fixtures/timeline/lumen/lumen/479.json' with { type: 'json' };
import f13 from '../fixtures/timeline/lumen/lumen/482.json' with { type: 'json' };
import f14 from '../fixtures/timeline/lumen/lumen/487.json' with { type: 'json' };
import f15 from '../fixtures/timeline/signalxjs/pulse/12.json' with { type: 'json' };
import f16 from '../fixtures/viewer-orgs.json' with { type: 'json' };
import f17 from '../fixtures/viewer-repos.json' with { type: 'json' };
import f18 from '../fixtures/viewer.json' with { type: 'json' };

/** @type {Record<string, any>} */
export const FIXTURES = {
    'collaborators/lumen/lumen.json': f0,
    'collaborators/signalxjs/pulse.json': f1,
    'issues/lumen/lumen.json': f2,
    'issues/signalxjs/pulse.json': f3,
    'labels/lumen/lumen.json': f4,
    'labels/signalxjs/pulse.json': f5,
    'milestones/lumen/lumen.json': f6,
    'milestones/signalxjs/pulse.json': f7,
    'owner-repos/signalxjs.json': f8,
    'repo/lumen/lumen.json': f9,
    'repo/signalxjs/core.json': f10,
    'repo/signalxjs/pulse.json': f11,
    'timeline/lumen/lumen/479.json': f12,
    'timeline/lumen/lumen/482.json': f13,
    'timeline/lumen/lumen/487.json': f14,
    'timeline/signalxjs/pulse/12.json': f15,
    'viewer-orgs.json': f16,
    'viewer-repos.json': f17,
    'viewer.json': f18,
};
